//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Autentificar_LDAPConnectionJAASHttpBinding", Namespace="http://infonavit.ejemplo.com/Binding2")]
public partial class Autentificar_LDAPConnectionJAASHttpBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback loguearOperationCompleted;
    
    /// <remarks/>
    public Autentificar_LDAPConnectionJAASHttpBinding() {
        this.Url = "https://10.90.8.208:9487/AutenticaLdap/autenticaService";
    }
    
    /// <remarks/>
    public event loguearCompletedEventHandler loguearCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://infonavit.ejemplo.com", ResponseNamespace="http://infonavit.ejemplo.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("loguearReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string loguear([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string usua, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string pwd) {
        object[] results = this.Invoke("loguear", new object[] {
                    usua,
                    pwd});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginloguear(string usua, string pwd, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("loguear", new object[] {
                    usua,
                    pwd}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endloguear(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void loguearAsync(string usua, string pwd) {
        this.loguearAsync(usua, pwd, null);
    }
    
    /// <remarks/>
    public void loguearAsync(string usua, string pwd, object userState) {
        if ((this.loguearOperationCompleted == null)) {
            this.loguearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloguearOperationCompleted);
        }
        this.InvokeAsync("loguear", new object[] {
                    usua,
                    pwd}, this.loguearOperationCompleted, userState);
    }
    
    private void OnloguearOperationCompleted(object arg) {
        if ((this.loguearCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.loguearCompleted(this, new loguearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LDAPConnectionJAASSoapBinding", Namespace="http://infonavit.ejemplo.com")]
public partial class LDAPConnectionJAASSoapBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback loguearOperationCompleted;
    
    /// <remarks/>
    public LDAPConnectionJAASSoapBinding() {
        this.Url = "http://10.90.1.31/ServicioAutentificacionConLDAP/services/LDAPConnectionJAAS";
    }
    
    /// <remarks/>
    public event loguearCompletedEventHandler loguearCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://infonavit.ejemplo.com", ResponseNamespace="http://infonavit.ejemplo.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("loguearReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string loguear([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string usua, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string pwd) {
        object[] results = this.Invoke("loguear", new object[] {
                    usua,
                    pwd});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginloguear(string usua, string pwd, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("loguear", new object[] {
                    usua,
                    pwd}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endloguear(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void loguearAsync(string usua, string pwd) {
        this.loguearAsync(usua, pwd, null);
    }
    
    /// <remarks/>
    public void loguearAsync(string usua, string pwd, object userState) {
        if ((this.loguearOperationCompleted == null)) {
            this.loguearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloguearOperationCompleted);
        }
        this.InvokeAsync("loguear", new object[] {
                    usua,
                    pwd}, this.loguearOperationCompleted, userState);
    }
    
    private void OnloguearOperationCompleted(object arg) {
        if ((this.loguearCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.loguearCompleted(this, new loguearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
public delegate void loguearCompletedEventHandler(object sender, loguearCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class loguearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal loguearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
