//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.7.3081.0.
// 
namespace Autenticacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_autenticaUsuario_SOBinding", Namespace="http://infonavit.org.mx/AUTENTICACION_TDS/sndAutenticacionUnificada")]
    public partial class SI_autenticaUsuario_SOService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_autenticaUsuario_SOOperationCompleted;
        
        /// <remarks/>
        public SI_autenticaUsuario_SOService() {
            this.Url = @"https://10.90.8.208:9487/AutenticaLdap/autenticaService";
        }
        
        /// <remarks/>
        public event SI_autenticaUsuario_SOCompletedEventHandler SI_autenticaUsuario_SOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", RequestElementName="login", RequestNamespace="http://ws.autentica.infonavit.mx.org/", ResponseElementName="loginResponse", ResponseNamespace="http://ws.autentica.infonavit.mx.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SI_autenticaUsuario_SO([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password) {
            object[] results = this.Invoke("SI_autenticaUsuario_SO", new object[] {
                        usuario,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSI_autenticaUsuario_SO(string usuario, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SI_autenticaUsuario_SO", new object[] {
                        usuario,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSI_autenticaUsuario_SO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SI_autenticaUsuario_SOAsync(string usuario, string password) {
            this.SI_autenticaUsuario_SOAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void SI_autenticaUsuario_SOAsync(string usuario, string password, object userState) {
            if ((this.SI_autenticaUsuario_SOOperationCompleted == null)) {
                this.SI_autenticaUsuario_SOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_autenticaUsuario_SOOperationCompleted);
            }
            this.InvokeAsync("SI_autenticaUsuario_SO", new object[] {
                        usuario,
                        password}, this.SI_autenticaUsuario_SOOperationCompleted, userState);
        }
        
        private void OnSI_autenticaUsuario_SOOperationCompleted(object arg) {
            if ((this.SI_autenticaUsuario_SOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_autenticaUsuario_SOCompleted(this, new SI_autenticaUsuario_SOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
    public delegate void SI_autenticaUsuario_SOCompletedEventHandler(object sender, SI_autenticaUsuario_SOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.3081.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_autenticaUsuario_SOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_autenticaUsuario_SOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
